---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubelet-csr-approver
  namespace: flux-system
spec:
  interval: 10m
  url: https://postfinance.github.io/kubelet-csr-approver