---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-operator.yaml
  - cilium.yaml
  - cnpg.yaml
  - dragonfly-operator.yaml
  - rook-release.yaml
  - metrics-server.yaml
  - kubelet-csr-approver.yaml
  - jetstack.yaml
  - victoria-metrics.yaml