---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nfd   
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v0.17.0
  url: https://github.com/kubernetes-sigs/node-feature-discovery