---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: stash
  namespace: flux-system
spec:
  interval: 10m0s
  url: oci://ghcr.io/appscode-charts/stash
  ref:
    tag: v2024.9.30