apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github
  namespace: flux-system
spec:
  type: github
  address: {GITHUB_INFRA_REPO}
  secretRef:
    name: github-commit-status