apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-secret-generator
  namespace: kubernetes-secret-generator
spec:
  interval: 10m
  chart:
    spec:
      chart: kubernetes-secret-generator
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
      version: '3.4.0'
  values:
