---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./config/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloudflare-operator
  wait: true