apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secrets
  namespace: cloudflare-operator-system
stringData:
  CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_OPERATOR_API_TOKEN}
  CLOUDFLARE_API_KEY: ${CLOUDFLARE_GLOBAL_API_KEY}