---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: tunnel-external
  namespace: cloudflare-operator-system
spec:
  newTunnel:
    name: lythrum
  size: 3
  cloudflare:
    email: ${CLOUDFLARE_EMAIL}
    domain: ${DOMAIN_EXTERNAL}
    secret: cloudflare-secrets
    accountId: ${CLOUDFLARE_ACCOUNT_ID}
  image: cloudflare/cloudflared:2024.12.2
  fallbackTarget: http_status:418