apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: filebrower
  namespace: media
spec:
  secretName: filebrowser-tls
  dnsNames:
    - ${SUBDOMAIN_MEDIA_FILEBROWSER}.${DOMAIN_INTERNAL}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod