apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent
  namespace: media
spec:
  secretName: qbittorrent-tls
  dnsNames:
    - ${SUBDOMAIN_QBITTORRENT}.${DOMAIN_INTERNAL}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod