---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: '3.6.0'
  values:
    controllers:
      qbittorrent:
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: '5.0.3'
            env:
              TZ: ${TIMEZONE}
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 50413
              PUSHOVER_ENABLED: true
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              runAsUser: 568
              runAsGroup: 568
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8Gi

          gluetun:
            dependsOn: app
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            env:
              VPN_SERVICE_PROVIDER: mullvad
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              WIREGUARD_PRIVATE_KEY: ${MULLVAD_PRIVATE_KEY}
              WIREGUARD_ADDRESSES: ${MULLVAD_ADDRESSES}
              SERVER_CITIES: ${MULLVAD_CITIES}
              DOT: 'off'
              PUBLICIP_API: cloudflare
            resources:
              limits:
                squat.ai/tun: "1"
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN

          port-forward:
            dependsOn: gluetun
            image:
              repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
              tag: "1.3"
            env:
              - name: QBITTORRENT_SERVER
                value: localhost
              - name: QBITTORRENT_PORT
                value: "8080"
              - name: PORT_FORWARDED
                value: /tmp/gluetun/forwarded_port

    service:
      app:
        controller: qbittorrent
        type: ClusterIP
        ports:
          http:
            port: *port
          bittorrent:
            enabled: true
            port: *torrentPort
            protocol: TCP

    persistence:
      config:
        storageClass: ceph-block-akane-nvme
        accessMode: ReadWriteOnce
        size: 1Gi
      media:
        existingClaim: media
      tmp:
        type: emptyDir