---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: '3.6.0'
  values:
    controllers:
      qbittorrent:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
          terminationGracePeriodSeconds: 60

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: '5.0.3'
            ports:
              - name: web
                containerPort: &qbtWebPort 8080
              - name: torrent
                containerPort: &qbtTorrentPort 50413
            env:
              TZ: ${TIMEZONE}
              QBT_WEBUI_PORT: *qbtWebPort
              QBT_TORRENTING_PORT: *qbtTorrentPort
            probes:
              liveness:
                enabled: true
                port: web
              readiness:
                enabled: true
                port: web
              startup:
                enabled: true
                port: web
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8Gi
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          gluetun:
            dependsOn: app
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            env:
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              WIREGUARD_IMPLEMENTATION: kernelspace
              WIREGUARD_PRIVATE_KEY: ${QBT_WG_PRIVATE_KEY}
              WIREGUARD_ADDRESSES: ${QBT_WG_ADDRESSES}
              WIREGUARD_PUBLIC_KEY: ${QBT_WG_PEER_PUBLIC_KEY}
              WIREGUARD_ENDPOINT_IP: ${QBT_WG_PEER_ENDPOINT_IP}
              WIREGUARD_ENDPOINT_PORT: ${QBT_WG_PEER_ENDPOINT_PORT}
              VPN_PORT_FORWARDING: 'on'
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              FIREWALL_INPUT_PORTS: *qbtWebPort
              FIREWALL_OUTBOUND_SUBNETS: 10.96.0.0/12,10.244.0.0/16
              DOT: 'off'
              PUBLICIP_API: cloudflare
            resources:
              limits:
                squat.ai/tun: "1"
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN

          port-forward:
            image:
              repository: ghcr.io/bjw-s-labs/gluetun-qb-port-sync
              tag: '0.0.2'
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *qbtWebPort
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      app:
        controller: qbittorrent
        type: ClusterIP
        ports:
          http:
            port: *qbtWebPort
          torrent:
            enabled: true
            port: *qbtTorrentPort
            protocol: TCP

    persistence:
      config:
        storageClass: ceph-block-akane-nvme
        accessMode: ReadWriteOnce
        size: 1Gi
      media:
        existingClaim: media
      tmp:
        type: emptyDir