apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
spec:
  interval: 10m
  chart:
    spec:
      chart: nvidia-device-plugin
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin
        namespace: flux-system
      version: '0.17.0'
  values:
    gfd:
      enabled: true
    nfd:
      enabled: false
    devicePlugin:
      enabled: false
    runtimeClassName: nvidia