apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: snapshot-controller
spec:
  interval: 10m
  chart:
    spec:
      chart: snapshot-controller
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
      version: '3.0.6'
