apiVersion: v1
kind: Secret
metadata:
  name: backblaze
  namespace: velero
stringData:
  key: >-
    [default]
    aws_access_key_id = ${BACKBLAZE_BACKUP_KEY_ID}
    aws_secret_access_key = ${BACKBLAZE_BACKUP_KEY_SECRET}