apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: autobrr
  namespace: media
spec:
  secretName: autobrr-tls
  dnsNames:
    - ${SUBDOMAIN_AUTOBRR}.${DOMAIN_INTERNAL}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod