---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: webhook-tunnel
  namespace: flux-system
subjects:
  - name: webhook-receiver
    spec:
      fqdn: ${SUBDOMAIN_FLUX_WEBHOOKS}.${DOMAIN_EXTERNAL}
tunnelRef:
  kind: ClusterTunnel
  name: tunnel-external