apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-pod-cidrs
  namespace: tailscale-operator
spec:
  hostname: ts-pod-cidrs
  exitNode: true
  subnetRouter:
    advertiseRoutes:
      - "10.40.0.0/14"