---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale-operator
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: '1.76.6'
  values:
    oauth:
      clientId: ${TAILSCALE_OAUTH_CLIENT_ID}
      clientSecret: ${TAILSCALE_OAUTH_CLIENT_SECRET}