apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr
  namespace: media
spec:
  secretName: radarr-tls
  dnsNames:
    - ${SUBDOMAIN_RADARR}.${DOMAIN_INTERNAL}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod