---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: "grafana"
spec:
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: ceph-block-nvme
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: admin
      admin_password: ${GRAFANA_ADMIN_PASSWORD}
  deployment:
    spec:
      template:
        spec:
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
