---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vicm
  namespace: monitoring
spec:
  interval: 10m0s
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
      version: '0.28.4'
  values:
    victoria-metrics-operator:
      crds:
        enabled: false

    vmsingle:
      spec:
        storage:
          accessModes:
            - ReadWriteOnce
          storageClassName: ceph-block-akane-nvme
          resources:
            requests:
              storage: 20Gi