apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: media-backup
  namespace: velero
spec:
  paused: false
  schedule: 0 0 * * *
  template:
    includedNamespaces:
      - media
    snapshotMoveData: true