apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser-http
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`fb.${DOMAIN_STAGING}`)
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: traefik
      services:
        - name: noop@internal
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser-https
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`fb.${DOMAIN_STAGING}`)
      kind: Rule
      services:
        - name: filebrowser
          port: 80
  tls:
    secretName: filebrowser-tls
