apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`fb.${DOMAIN_STAGING}`)
      kind: Rule
      services:
        - name: filebrowser
          port: 80
  tls:
    secretName: filebrowser-tls
