kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ceph-fs-bridget-hdd
  volumeMode: Filesystem
