kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: torrents
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
  storageClassName: fs-akane-nvme
  volumeMode: Filesystem
