---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: jellyfin-tunnel
  namespace: media
subjects:
  - name: jellyfin
    spec:
      fqdn: ${SUBDOMAIN_JELLYFIN}.${DOMAIN_EXTERNAL}
tunnelRef:
  kind: ClusterTunnel
  name: tunnel-external