---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: '33.2.1'
  values:
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
    gateway:
      namespacePolicy: All
    service:
      type: ClusterIP
      annotations:
        tailscale.com/expose: 'true'
        tailscale.com/hostname: traefik