---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: '33.2.1'
  values:
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
      kubernetesGateway:
        enabled: false
    ingressRoute:
      dashboard:
        enabled: true
    deployment:
      additionalContainers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:v1.78.3
          imagePullPolicy: IfNotPresent
          env:
            - name: TS_KUBE_SECRET
              value: tailscale-auth
            - name: TS_HOSTNAME
              value: traefik
            - name: TS_USERSPACE
              value: "false"
            - name: TS_DEBUG_FIREWALL_MODE
              value: auto
            - name: TS_AUTHKEY
              value: ${TAILSCALE_AUTHKEY}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          resources:
            limits:
              squat.ai/tun: "1"
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW

    securityContext:
      capabilities:
        drop:
          - ALL
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false

    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch

    service:
      enabled: false
      # type: LoadBalancer
      # spec:
      #   loadBalancerClass: tailscale
      # annotations:
      #   tailscale.com/expose: 'true'
      #   tailscale.com/hostname: traefik
      #   external-dns.alpha.kubernetes.io/hostname: traefik.${DOMAIN_INTERNAL}