---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey-operator
  namespace: valkey-operator
spec:
  interval: 10m0s
  chartRef:
    kind: OCIRepository
    name: valkey-operator
    namespace: flux-system