---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ot-redis-operator
  namespace: ot-operators
spec:
  interval: 10m0s
  chart:
    spec:
      chart: redis-operator
      sourceRef:
        kind: HelmRepository
        name: opstree
        namespace: flux-system
      version: '0.18.1'