---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: dragonfly-system
spec:
  interval: 10m
  chart:
    spec:
      chart: dragonfly-operator
      sourceRef:
        kind: HelmRepository
        name: flux-system
      version: v1.1.8