---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: volume-snapshot-crds
  namespace: flux-system
spec:
  interval: 15m
  ref:
    tag: release-8.1
  url: https://github.com/kubernetes-csi/external-snapshotter
  ignore: |
    # exclude all
    /*
    # include crds file
    !/client/config/crd/*_volumesnapshots.yaml