---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: grafana
spec:
  config:
    log:
      mode: "console"
    auth:
      signout_redirect_url: "https://${SUBDOMAIN_AUTHENTIK}.${DOMAIN_EXTERNAL}/application/o/grafana/end-session/"
      oauth_auto_login: "true"
      disable_login_form: "true"
    auth.generic_oauth:
      name: authentik
      enabled: "true"
      client_id: ${AUTHENTIK_GRAFANA_CLIENT_ID}
      client_secret: ${AUTHENTIK_GRAFANA_CLIENT_SECRET}
      scopes: "openid profile email"
      auth_url: "https://${SUBDOMAIN_AUTHENTIK}.${DOMAIN_EXTERNAL}/application/o/authorize/"
      token_url: "https://${SUBDOMAIN_AUTHENTIK}.${DOMAIN_EXTERNAL}/application/o/token/"
      api_url: "https://${SUBDOMAIN_AUTHENTIK}.${DOMAIN_EXTERNAL}/application/o/userinfo/"
      role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
    server:
      root_url: https://${SUBDOMAIN_GRAFANA}.${DOMAIN_INTERNAL}/
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana:11.3.1