apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: vicm
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: vm1
    type: prometheus
    access: proxy
    url: http://vmsingle-vicm-victoria-metrics-k8s-stack.monitoring.svc.cluster.local:8429
    isDefault: true
    jsonData:
      "tlsSkipVerify": true
      "timeInterval": "5s"
