apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: generic-device-plugin
  namespace: kube-system
spec:
  interval: 10m
  prune: true
  path: ./manifests
  sourceRef:
    kind: GitRepository
    name: generic-device-plugin
    namespace: flux-system