apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: generic-device-plugin
  namespace: kube-system
spec:
  interval: 10m
  prune: true
  path: ./manifests
  sourceRef:
    kind: GitRepository
    name: generic-device-plugin
    namespace: flux-system
  patches:
    - target:
        kind: DaemonSet
        name: generic-device-plugin
      patch: |-
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: |
            --device='{"name": "tun", "groups": [{"paths": [{"path": "/dev/net/tun"}]}, "count": 1000]}'