---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: kubelet-csr-approver
      sourceRef:
        kind: HelmRepository
        name: kubelet-csr-approver
        namespace: flux-system
      version: '1.2.3'
  values:
    leaderElection: true
    replicas: 2
    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
    providerRegex: ^.+$