---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: '3.12.2'
  values:
    replicas: 2
    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule