apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-operator-system
  - flux-system
  - kube-system
  - cnpg-system
  - cert-manager
  - monitoring
  - rook-ceph
  - tailscale-operator
  - authentik
  - importer
  - velero
  - snapshot-controller
  - kubernetes-secret-generator
  - node-feature-discovery
  - nvidia-device-plugin