apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-operator-system
  - flux-system
  - kube-system
  - cnpg-system
  - rook-ceph
  - rook-ceph-bridget
  - cert-manager
  - monitoring
  - tailscale-operator
  - ot-operators
  - authentik
