apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-operator-system
  - flux-system
  - kube-system
  - cnpg-system
  - cert-manager
  - monitoring
  - rkc-bridget
  - rkc-akane
  - rook-ceph
  - tailscale-operator
  - ot-operators
  - authentik
  - importer
  - velero
  - snapshot-controller