apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 10m
  prune: true
  path: ./deployment/overlays/default
  sourceRef:
    kind: GitRepository
    name: nfd
    namespace: flux-system
  patches:
    # remove Namespaces from the kustomization
    - target:
        kind: Namespace
      patch: |-
        $patch: delete
        apiVersion: v1
        kind: Namespace
        metadata:
          name: h
