apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: importer-data
  namespace: importer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Ti
  storageClassName: ceph-block-bridget-hdd