apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: importer-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: ceph-block-bridget-hdd