apiVersion: v1
kind: Service
metadata:
  name: importer-service
  namespace: importer
spec:
  selector:
    app: importer
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22