apiVersion: v1
kind: Service
metadata:
  name: importer-service
  namespace: importer
spec:
  selector:
    app: importer
  type: NodePort
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30222