---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: external-secrets-crds
  interval: 15m
  prune: false
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: external-secretss.external-secrets.io