apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: authentik-backup
  namespace: velero
spec:
  paused: false
  schedule: 0 0 * * *
  template:
    includedNamespaces:
      - authentik
    snapshotMoveData: true