apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: authentik-backup
  namespace: velero
spec:
  paused: false
  schedule: 30 1 * * *
  template:
    includedNamespaces:
      - authentik
    excludedResources:
      - events.k8s.io
    snapshotMoveData: true