---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 10m
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      version: '2024.10.4'
  values:
    authentik:
      secret_key: ${AUTHENTIK_SECRET_KEY}
      postgresql:
        host: postgres-rw.authentik.svc.cluster.local
        user: file:///var/run/secrets/postgres/username
        password: file:///var/run/secrets/postgres/password
      redis:
        host: redis.authentik.svc.cluster.local
    server:
      volumes:
        - name: postgres-creds
          secret:
            secretName: postgres-app
      volumeMounts:
        - name: postgres-creds
          mountPath: /var/run/secrets/postgres
          readOnly: true
    worker:
      volumes:
        - name: postgres-creds
          secret:
            secretName: postgres-app
      volumeMounts:
        - name: postgres-creds
          mountPath: /var/run/secrets/postgres
          readOnly: true
