apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-backup
  namespace: authentik
spec:
  immediate: true
  schedule: "0 0 */12 * * *"
  backupOwnerReference: self
  cluster:
    name: postgres