apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: authentik
spec:
  instances: 1
  storage:
    storageClass: ceph-block-akane-nvme
    size: 8Gi
  monitoring:
    enablePodMonitor: true