---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis
  namespace: authentik
spec:
  kubernetesConfig:
    image: docker.io/valkey/valkey:8.0.1-alpine
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: ceph-block-nvme
        resources:
          requests:
            storage: 1Gi
