---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 15m
  ref:
    tag: v1.2.1
  url: https://github.com/kubernetes-sigs/gateway-api
  ignore: |
    # exclude all
    /*
    # include crds directory
    !/config/crd/standard