apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hr.yaml
  - api-key.secret.yaml
configMapGenerator:
  - name: cross-seed-config
    namespace: media
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    files:
      - config/config.js
configurations:
  - kustomizeconfig.yaml