apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami
  namespace: traefik
spec:
  secretName: whoami-tls
  dnsNames:
    - whoami.${DOMAIN_EXTERNAL}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod