---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cloudflare-operator-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: cloudflare-operator-crds
  interval: 15m
  prune: false
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clustertunnels.networking.cfargotunnel.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: tunnelbindings.networking.cfargotunnel.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: tunnels.networking.cfargotunnel.com