---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudflare-operator-crds
  namespace: flux-system
spec:
  interval: 15m
  ref:
    tag: v1.15.5
  url: https://github.com/adyanth/cloudflare-operator
  ignore: |
    # exclude all
    /*
    # include crds directory
    !/config/crd