apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-gpu-nfd-rules
  namespace: intel-gpu-plugin
spec:
  interval: 10m
  prune: true
  path: ./deployments/nfd/overlays/node-feature-rules/
  sourceRef:
    kind: GitRepository
    name: intel-ks
    namespace: flux-system
