apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfd-rules
  namespace: intel-gpu-plugin
spec:
  interval: 10m
  prune: true
  path: ./deployments/nfd/overlays/node-feature-rules/
  sourceRef:
    kind: GitRepository
    name: intel-ks
    namespace: flux-system
  patches:
    - target:
        kind: DaemonSet
      patch: |-
        $patch: replace
        metadata:
          namespace: intel-gpu-plugin