apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plugin
  namespace: intel-gpu-plugin
spec:
  interval: 10m
  prune: true
  path: ./deployments/gpu_plugin/overlays/nfd_labeled_nodes
  sourceRef:
    kind: GitRepository
    name: intel-ks
    namespace: flux-system
  patches:
      - target:
          kind: DaemonSet
        patch: |-
          - op: replace
            path: /metadata/namespace
            value: intel-gpu-plugin