apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyseerr
  namespace: media
spec:
  secretName: jellyseerr-tls
  dnsNames:
    - ${SUBDOMAIN_JELLYSEERR}.${DOMAIN_INTERNAL}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod