---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "3.6.0"
  values:
    controllers:
      jellyseerr:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          annotations:
            backup.velero.io/backup-volumes: config

        containers:
          app:
            image:
              repository: fallenbagel/jellyseerr
              tag: "2.5.1"
            ports:
              - name: http
                containerPort: &port 5055
            env:
              TZ: ${TIMEZONE}
              PORT: *port
              LOG_LEVEL: debug
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    service:
      app:
        controller: jellyseerr
        type: ClusterIP
        ports:
          http:
            port: *port

    persistence:
      config:
        storageClass: ceph-block-akane-nvme
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /app/config
      tmp:
        type: emptyDir
