---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana-operator-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: grafana-operator-crds
  interval: 15m
  prune: false
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: grafanaalertrulegroups.grafana.integreatly.org
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: grafanacontactpoints.grafana.integreatly.org
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: grafanadashboards.grafana.integreatly.org
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: grafanadatasources.grafana.integreatly.org
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: grafanafolders.grafana.integreatly.org
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: grafananotificationpolicies.grafana.integreatly.org
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: grafanas.grafana.integreatly.org