apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: sonarr-api-key
  namespace: media
spec:
  forceRegenerate: false
  fields:
    - fieldName: key
      encoding: hex
      length: '32'