apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr
  namespace: media
spec:
  secretName: sonarr-tls
  dnsNames:
    - ${SUBDOMAIN_SONARR}.${DOMAIN_INTERNAL}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod