apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clustersecret
  namespace: clustersecret
spec:
  interval: 10m
  chart:
    spec:
      chart: clustersecret
      sourceRef:
        kind: HelmRepository
        name: clustersecret
        namespace: flux-system
      version: '0.4.5'
  values: