apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: jellyfin-backup
  namespace: velero
spec:
  paused: false
  schedule: 0 0 * * *
  template:
    includedNamespaces:
      - jellyfin
    snapshotMoveData: true