---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: victoria-metrics-operator-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: victoria-metrics-operator-crds
  interval: 15m
  prune: false
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vlogs.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmagents.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmalertmanagerconfigs.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmalertmanagers.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmalerts.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmauths.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmclusters.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmnodescrapes.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmpodscrapes.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmprobes.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmrules.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmscrapeconfigs.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmservicescrapes.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmsingles.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmstaticscrapes.operator.victoriametrics.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vmusers.operator.victoriametrics.com
