apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: paperless
  namespace: paperless
spec:
  secretName: paperless-tls
  dnsNames:
    - ${SUBDOMAIN_PAPERLESS}.${DOMAIN_INTERNAL}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod