apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: paperless
  namespace: paperless
spec:
  forceRegenerate: false
  fields:
    - fieldName: secret_key
      encoding: hex
      length: '64'