# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# An empty starter config to use with Recyclarr. Update the values below as needed for your
# instance. You will be required to update the `api_key` and `base_url` for each instance you want
# to use.
#
# If you'd rather use pre-built configuration instead of building your own from scratch, see these
# pages:
# - Config Templates: https://recyclarr.dev/wiki/guide-configs/
# - CLI Command: https://recyclarr.dev/wiki/cli/config/list/templates/
#
# This file WILL NOT WORK as it currently is. You need to read the documentation and build this
# configuration from scratch. Note that there's no "one size fits all" configuration. Please refer
# to the TRaSH Guides to understand how to build the appropriate configuration based on your
# hardware setup and capabilities.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/
#
# Want a more flexible file layout?
# See: https://recyclarr.dev/wiki/file-structure/

# Configuration specific to Sonarr. For Radarr, the layout is the same.
# See: https://recyclarr.dev/wiki/yaml/config-reference/basic/
sonarr:
  series:
    base_url: !env_var SONARR_URL
    api_key: !env_var SONARR_API_KEY

    include:
      - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime

    # See: https://recyclarr.dev/wiki/yaml/config-reference/quality-profiles/
    # quality_profiles: []

    # See: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    custom_formats:
      # block
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
          - 23297a736ca77c0fc8e70f8edd7ee56c # Upscaled
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title)
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)
        assign_scores_to:
          - name: WEB-1080p
            score: -10000
          - name: Remux-1080p - Anime
            score: -10000

      # -20
      - trash_ids:
          - cddfb4e32db826151d97352b8e37c648 # x264
          - bd6dd5e043aa27ff4696a08d011c7d96 # mono audio
        assign_scores_to:
          - name: WEB-1080p
            score: -20
          - name: Remux-1080p - Anime
            score: -20

      # zero
      - trash_ids:
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: WEB-1080p
            score: 0
          - name: Remux-1080p - Anime
            score: 0

      # +10
      - trash_ids:
          - 3bc5f395426614e155e585a2f056cdf1 # Season Pack
        assign_scores_to:
          - name: WEB-1080p
            score: 10
          - name: Remux-1080p - Anime
            score: 10

      # +100
      - trash_ids:
          - c9eafd50846d299b862ca9bb6ea91950 # x265
          - 15a05bc7c1a36e2b57fd628f8977e2fc # av1
          - 90501962793d580d011511155c97e4e5 # vp9
        assign_scores_to:
          - name: WEB-1080p
            score: 100
          - name: Remux-1080p - Anime
            score: 100

      # defaults
      - trash_ids:
          - fbcb31d8dabd2a319072b84fc0b7249c # Hybrid
          - b735f09d3c025cbb7d75a5d38325b73b # Remaster
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack v2
          - 44e7c4de10ae50265753082e5dc76047 # Repack v3
          - d7c747094a7c65f4c2de083c24899e8b # Freeleech
        assign_scores_to:
          - name: WEB-1080p
          - name: Remux-1080p - Anime

      ### Anime
      - trash_ids:
        - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 100

      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 50

    # See: https://recyclarr.dev/wiki/yaml/config-reference/media-naming/
    media_naming:
      series: jellyfin
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

radarr:
  hd-bluray-web:
    base_url: !env_var RADARR_URL
    api_key: !env_var RADARR_API_KEY

    include:
      # Comment out any of the following includes to disable them
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web

    media_naming:
      folder: jellyfin-imdb
      movie:
        rename: true
        standard: jellyfin-imdb