---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: '3.6.0'
  values:
    controllers:
      recyclarr:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          annotations:
            backup.velero.io/backup-volumes: config

        containers:
          app:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: '7.4.0'
            env:
              TZ: ${TIMEZONE}
              CRON_SCHEDULE: 0 * * * *

              SONARR_URL: http://sonarr:8989
              SONARR_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sonarr-api-key
                    key: key

              RADARR_URL: http://radarr:7878
              RADARR_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: radarr-api-key
                    key: key
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    persistence:
      config:
        type: configMap
        name: recyclarr-config
        globalMounts:
          - path: /config/recyclarr.yaml
            subPath: recyclarr.yaml
      cache:
        storageClass: ceph-block-akane-nvme
        accessMode: ReadWriteOnce
        size: 128Mi
        globalMounts:
          - path: /config/cache
      repositories:
        storageClass: ceph-block-akane-nvme
        accessMode: ReadWriteOnce
        size: 512Mi
        globalMounts:
          - path: /config/repositories
      tmp:
        type: emptyDir