---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: '3.6.0'
  values:
    controllers:
      recyclarr:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          terminationGracePeriodSeconds: 60

        containers:
          app:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: '7.4.0'
            env:
              TZ: ${TIMEZONE}
              CRON_SCHEDULE: 0 * * * *
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    persistence:
      config:
        enabled: false
        type: configMap
        name: recyclarr-config
        globalMounts:
          - path: /config/config.yml
            subPath: config.yaml