apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hr.yaml
configMapGenerator:
  - name: recyclarr-config
    namespace: media
    files:
      - config.yaml
configurations:
  - kustomizeconfig.yaml