---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rook-ceph-crds
  namespace: flux-system
spec:
  interval: 15m
  ref:
    tag: v1.15.5
  url: https://github.com/rook/rook
  ignore: |
    # exclude all
    /*
    # include crds file
    !/deploy/examples/crds.yaml