apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: dns
subjects:
  - kind: ServiceAccount
    name: coredns
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io