---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: external-secrets-crds
  interval: 15m
  prune: false
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusterexternalsecrets.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clustersecretstores.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: externalsecrets.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: pushsecrets.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: secretstores.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: acraccesstokens.generators.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clustergenerators.generators.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ecrauthorizationtokens.generators.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: fakes.generators.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: gcraccesstokens.generators.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: githubaccesstokens.generators.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: passwords.generators.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: quayaccesstokens.generators.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: stssessiontokens.generators.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: uuids.generators.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vaultdynamicsecrets.generators.external-secrets.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: webhooks.generators.external-secrets.io