---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-secrets-crds
  namespace: flux-system
spec:
  interval: 15m
  ref:
    tag: 'v0.13.0'
  url: https://github.com/external-secrets/external-secrets
  ignore: |
    # exclude all
    /*
    # include crds directory
    !/deploy/crds/bundle.yaml