{
 "title": "Ceph Cluster",
 "description": "Overview of your Ceph cluster.",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "Cluster",
    "query": {
     "query": "label_values(ceph_health_status,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ceph health status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_health_status{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_used_bytes{namespace=\"$namespace\"})/ceph_cluster_total_bytes{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_objects{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_op_w_in_bytes{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_op_r_out_bytes{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Alerts starting with Ceph",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",alertname=~\"^Ceph.+\",namespace=\"$namespace\"}) OR vector(0)"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r{namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "sum(ceph_pool_objects)" }
   ]
  },
  {
   "title": "Mon Session Num",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mon_num_sessions{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_mon_quorum_status{namespace=\"$namespace\"}) or vector(0)"
    }
   ]
  },
  { "title": "OSD State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{namespace=\"$namespace\"}) - count(ceph_osd_in{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{namespace=\"$namespace\"} == 0.0) OR vector(0)"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_in{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Avg PGs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_numpg{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Avg Op Write Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum{namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_w_latency_count{namespace=\"$namespace\"}[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "Avg Op Read Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum{namespace=\"$namespace\"}[5m])/rate(ceph_osd_op_r_latency_count{namespace=\"$namespace\"}[5m]) >= 0)"
    }
   ]
  },
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{namespace=\"$namespace\"}-ceph_cluster_total_used_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "ceph_cluster_total_used_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "ceph_cluster_total_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Cluster Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Pool Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_bytes_used{namespace=\"$namespace\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{namespace=\"$namespace\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool RAW Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_avail_raw{namespace=\"$namespace\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{namespace=\"$namespace\"})",
     "legendFormat": "{{name}} Avail"
    },
    {
     "expr": "(ceph_pool_stored_raw{namespace=\"$namespace\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{namespace=\"$namespace\"})",
     "legendFormat": "{{name}} Stored"
    }
   ]
  },
  {
   "title": "Objects Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_objects{namespace=\"$namespace\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{namespace=\"$namespace\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Quota Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_bytes{namespace=\"$namespace\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{namespace=\"$namespace\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Quota",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_objects{namespace=\"$namespace\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{namespace=\"$namespace\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "OSD Type Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(ceph_bluestore_kv_commit_lat_count{namespace=\"$namespace\"})",
     "legendFormat": "BlueStore"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Alerts starting with Ceph",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ALERTS{namespace=\"$namespace\",alertstate=\"firing\",alertname=~\"^Ceph.+\"}"
    }
   ]
  },
  {
   "title": "Top Sluggish OSDs",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,sort_desc(ceph_osd_apply_latency_ms{namespace=\"$namespace\"} + ceph_osd_commit_latency_ms{namespace=\"$namespace\"}))",
     "legendFormat": "_auto"
    }
   ]
  },
  {
   "title": "Down OSDs",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_osd_up{namespace=\"$namespace\"} == 0"
    }
   ]
  },
  { "title": "Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "OSD Type Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pool_objects)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "PGs State",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pg_active{namespace=\"$namespace\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(ceph_pg_clean{namespace=\"$namespace\"})",
     "legendFormat": "Clean"
    },
    {
     "expr": "sum(ceph_pg_peering{namespace=\"$namespace\"})",
     "legendFormat": "Peering"
    },
    {
     "expr": "sum(ceph_pg_degraded{namespace=\"$namespace\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{namespace=\"$namespace\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_unclean_pgs{namespace=\"$namespace\"})",
     "legendFormat": "Unclean"
    },
    {
     "expr": "sum(ceph_pg_undersized{namespace=\"$namespace\"})",
     "legendFormat": "Undersized"
    },
    {
     "expr": "sum(ceph_pg_incomplete{namespace=\"$namespace\"})",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum(ceph_pg_forced_backfill{namespace=\"$namespace\"})",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "sum(ceph_pg_forced_recovery{namespace=\"$namespace\"})",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "sum(ceph_pg_creating{namespace=\"$namespace\"})",
     "legendFormat": "Creating"
    },
    {
     "expr": "sum(ceph_pg_wait_backfill{namespace=\"$namespace\"})",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "sum(ceph_pg_deep{namespace=\"$namespace\"})",
     "legendFormat": "Deep"
    },
    {
     "expr": "sum(ceph_pg_scrubbing{namespace=\"$namespace\"})",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "sum(ceph_pg_recovering{namespace=\"$namespace\"})",
     "legendFormat": "Recovering"
    },
    {
     "expr": "sum(ceph_pg_repair{namespace=\"$namespace\"})",
     "legendFormat": "Repair"
    },
    {
     "expr": "sum(ceph_pg_down{namespace=\"$namespace\"})",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(ceph_pg_peered{namespace=\"$namespace\"})",
     "legendFormat": "Peered"
    },
    {
     "expr": "sum(ceph_pg_backfill{namespace=\"$namespace\"})",
     "legendFormat": "Backfill"
    },
    {
     "expr": "sum(ceph_pg_remapped{namespace=\"$namespace\"})",
     "legendFormat": "Remapped"
    },
    {
     "expr": "sum(ceph_pg_backfill_toofull{namespace=\"$namespace\"})",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pg_degraded{namespace=\"$namespace\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{namespace=\"$namespace\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_pg_undersized{namespace=\"$namespace\"})",
     "legendFormat": "Undersized"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{namespace=\"$namespace\"}[$interval]))",
     "legendFormat": "OPS"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "ceph_osd_commit_latency_ms{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "OSD Read Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_latency_sum{namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_r_latency_count{namespace=\"$namespace\"}[5m]) >= 0"
    }
   ]
  },
  {
   "title": "OSD Write Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_w_latency_sum{namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_w_latency_count{namespace=\"$namespace\"}[5m]) >= 0"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum{namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_r_latency_count{namespace=\"$namespace\"}[5m]) >= 0)",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum{namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_w_latency_count{namespace=\"$namespace\"}[5m]) >= 0)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{namespace=\"$namespace\"})",
     "legendFormat": "apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{namespace=\"$namespace\"})",
     "legendFormat": "commit"
    }
   ]
  },
  { "title": "Ceph Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Ceph OSD Versions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_osd_metadata{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Ceph Mon Versions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_mon_metadata{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Ceph MDS Versions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_mds_metadata{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Ceph RGW Versions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_rgw_metadata{namespace=\"$namespace\"})"
    }
   ]
  }
 ]
}