apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-operaotr
  namespace: rook-ceph
spec:
  interval: 10m
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      version: '1.15.6'
  values:
    crds:
      enabled: false
    monitoring:
      enabled: false
    csi:
      serviceMonitor:
        enabled: false
