apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rkc-operator
  namespace: rkc-bridget
spec:
  interval: 10m
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      version: '1.15.5'
  values:
    crds:
      enabled: false
    monitoring:
      enabled: true
    csi:
      serviceMonitor:
        enabled: true
